README.md
=> Adding Instacart

README.md
=> adding Tettra

README.md
=> Adds Braid

README.md
=> Adding Buffer

README.md
=> Add Heap to company list.

README.md
Chatted with a friend of mine who works there
=> Add Affirm

README.md
Added YC companies from this [list](https://triplebyte.com/ycombinator-startups) that have extended option exercise windows.
=> Add YC companies

README.md
Another "after 2 years of employment" situation.
=> Add Puppet's 1 year term to list

README.md
We just adopted this policy as well. Yay!
=> Add Ladder to the list

README.md
=> Add details for Checkr

README.md
https://github.com/clippings/join-us/blob/master/share-options.md#readme
Hi! I'm the CTO of Clippings. Thank you for maintaining this list! We'd like to add Clippings to the companies with a long exercise window
=> Add Clippings 10 year exercise window

README.md
I'm an engineer at Gusto and would like to clarify our policy as it currently stands :)
=> Update Gusto details

README.md
I suffered from a very short 90 exercise window in a previous startup, so now I'm making sure my new startup (@wasmerio) helps employees with a longer exercise period.
Great work on your blogpost btw! :)
=> Added @wasmerio to the list

README.md
=> Adds AngelList

README.md
=> Markdown errata

README.md
Source: I'm currently an Engineering Manager at Saleswhale.
=> docs: Add Saleswhale to list

README.md
source: I used to work at Affirm
=> add additional detail for Affirm

README.md
I am a co-founder of Intellimize. We have a 2 year exercise window.
=> Add Intellimize

README.md
Love the list -- It's about time this became the norm!
=> Add Postscript

README.md
Love this project, thank you!!
=> Add Buildkite

README.md
I am a cofounder of [Alan](alan.com) and I'm adding it to the list as we have a 7 years window.
More on Alan: https://techcrunch.com/2021/04/19/alan-raises-220-million-for-its-health-insurance-and-healthcare-super-app/
=> Adding Alan to the list

README.md
Rewatch has a sane exercise window, so I put it on the list!
=> Add Rewatch

README.md
=> Add OpsLevel.

README.md
Edits:
- Alien Labs (Got acquired)
- Cymmetria (Acquired)
- Supply (Acquired)
Removes:
- TrueAccord (Unclear, but they deleted the blog post)
Aside: All the triplebyte links are now broken.
=> Updates for acquired companies

README.md
- Affirm, Coinbase, and Pinterest went public (RSUs now)
- Segment was acquired by Twilio (RSUs now)
- Clef shut down
=> Moved some IPO'd, acquired and shutdown companies into the "Previously" section

README.md
=> Add Render (render.com) early exercise

README.md
Hey @holman, thanks for maintaining this list!
=> Adds WizeHire to the list

README.md
Instacart now grants double-trigger RSUs
=> Add Temporal; Move Instacart to previous

README.md
Great resource, thanks! We don't publish equity terms on our careers page yet, but there are details at:
- https://www.datacamp.com/careers and
- https://blog.datacamp.engineering/we-took-the-pragmatic-engineer-test-and-scored-12-out-of-12-db5861bc6d1f
=> Add DataCamp

README.md
Thanks for maintaining this list! I've been linking to it in a stock options explainer presentation since 2017!
=> Add Netlify

README.md
Company had a rebrand! We're Agora now!
=> Change Figure to Agora

README.md
https://www.toplyne.io/esop-policy -- it is public info that we are esop friendly
=> adding that toplyne.io is offering 10 yr

README.md
👋 I'm the co-founder of Mojo, and have been recommended to add our company there as we now offer an extended 10 years window.
https://twitter.com/matthieurouif/status/1518193264528134145
=> Add Mojo 🔥

README.md
Dear @holman,
I'm Julio, Zefir's Engineering & Data Lead. Please add Zefir to your list, we have a 10 year exercise window with a double trigger extra clause to ensure employees' safety.
Cheers
Julio
=> Add Zefir(www.zefir.fr) to startups list

README.md
Adding Vested.co to list. "Equity can change your life. Take charge of yours today"
=> Adding vested.co

README.md
Revolut introduced a 10-year exercise window in 2020:
https://sifted.eu/articles/revolut-share-options/
=> Add Revolut

README.md
=> Add Replicate

README.md
=> Add RunwayML

README.md
Wasmer is no longer offering extended exercise windows
=> Wasmer is no longer offering extended exercise windows

README.md
agora was acquired by payscale https://www.getagora.com/post/agora-announces-acquisition-by-payscale
=> remove Agora

README.md
Thanks for maintaining this list! I read your blog post way back when and was reminded of it when I recently joined BillionToOne where we also have this benefit!
=> Update README.md with BillionToOne

README.md
Adding my employer to this list, which has a 10-year exercise window!
=> Add Bobsled to list + fix alphabetical

README.md
Nine years ago when I started this repo, I didn't really expect it to take off like it did, and I didn't even think I'd be making my *own* contributions to it. Luckily I can now!
This adds [WorkOn](https://workon.co) to the mix, my sports/tech startup I'm building. More details to come, of course, but I thought it was just exciting to add our startup to the mix in the meantime.
=> Add my own startup: WorkOn

README.md
Added chameleon.io (I'm the co-founder & CEO)
=> Added another company (Chameleon)
